title = "Gallery"
defaultContentLanguage = "en"
languageCode = "en"

[module]
  [[module.imports]]
    path = "github.com/mdfriday/theme-gallery"

[menu]
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
  name = "Nature"
  url = "/nature/"
  weight = 2
[[menu.main]]
name = "About"
url = "/about.html"
weight = 3
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/nicokaiser/hugo-theme-gallery/"
    weight = 3

[params]
defaultTheme = "dark"